"""add editor_state and exported_at to jobs

Revision ID: 1b254e9e8620
Revises: d697edf17fc9
Create Date: 2026-04-23 09:37:13.691782
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1b254e9e8620"
down_revision: Union[str, None] = "d697edf17fc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "editor_state", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
    )
    op.add_column("jobs", sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "exported_at")
    op.drop_column("jobs", "editor_state")
    # ### end Alembic commands ###
