"""add password_reset_at to users

Revision ID: 4b6ee1a62487
Revises: 65e8c948ba07
Create Date: 2026-04-05 17:21:53.220040
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b6ee1a62487'
down_revision: Union[str, None] = '65e8c948ba07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_at')
    # ### end Alembic commands ###
