"""add otp_attempts to users

Revision ID: 65e8c948ba07
Revises: e3e606f12b81
Create Date: 2026-04-05 17:18:24.446043
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65e8c948ba07'
down_revision: Union[str, None] = 'e3e606f12b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_purchases_status'), table_name='credit_purchases')
    op.drop_index(op.f('ix_credit_purchases_user_id'), table_name='credit_purchases')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_purchases_user_id'), 'credit_purchases', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_purchases_status'), 'credit_purchases', ['status'], unique=False)
    # ### end Alembic commands ###
