"""add credit_purchases table and job pending_credits

Revision ID: 7fcbb15390c7
Revises: 8df32cbf67fc
Create Date: 2026-04-04 19:25:15.947882
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fcbb15390c7'
down_revision: Union[str, None] = '8df32cbf67fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=50), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('price_brl', sa.Integer(), nullable=False),
    sa.Column('mp_payment_id', sa.String(length=255), nullable=True),
    sa.Column('mp_preference_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('pending_credits', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.alter_column('jobs', 'template_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'stock_narration'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'template_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'stock_narration'::character varying"))
    op.drop_column('jobs', 'pending_credits')
    op.drop_table('credit_purchases')
    # ### end Alembic commands ###
