"""add_utm_referral_fields_to_users

Revision ID: a8a59ff9f7fd
Revises: f2b6c6a9d51b
Create Date: 2026-04-05 11:26:53.944397
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db.types import GUID

revision: str = "a8a59ff9f7fd"
down_revision: Union[str, None] = "4b6ee1a62487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("utm_source", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("utm_medium", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("utm_campaign", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("referral_code", sa.String(length=12), nullable=True))
    # Backfill existing users with unique referral codes
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id FROM users WHERE referral_code IS NULL"))
    import uuid

    for row in users:
        code = uuid.uuid4().hex[:8]
        conn.execute(sa.text("UPDATE users SET referral_code = :code WHERE id = :id"), {"code": code, "id": row[0]})
    op.alter_column("users", "referral_code", nullable=False)
    op.add_column("users", sa.Column("referred_by", GUID(length=36), nullable=True))
    op.create_unique_constraint("uq_users_referral_code", "users", ["referral_code"])
    op.create_foreign_key(None, "users", "users", ["referred_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_referred_by_fkey", "users", type_="foreignkey")
    op.drop_constraint("uq_users_referral_code", "users", type_="unique")
    op.drop_column("users", "referred_by")
    op.drop_column("users", "referral_code")
    op.drop_column("users", "utm_campaign")
    op.drop_column("users", "utm_medium")
    op.drop_column("users", "utm_source")
    # ### end Alembic commands ###
