"""add email verification fields to users

Revision ID: b5c55cc9bcac
Revises: 7fcbb15390c7
Create Date: 2026-04-04 20:25:27.272795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5c55cc9bcac'
down_revision: Union[str, None] = '7fcbb15390c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
