"""add_voice_clones_and_voice_fields_to_job

Revision ID: d697edf17fc9
Revises: a8a59ff9f7fd
Create Date: 2026-04-05 11:56:22.432412
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

from alembic import op

revision: str = "d697edf17fc9"
down_revision: Union[str, None] = "a8a59ff9f7fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "voice_clones",
        sa.Column("id", PG_UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", PG_UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_voice_id", sa.String(length=255), nullable=False),
        sa.Column("samples_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voice_clones_user_id"), "voice_clones", ["user_id"], unique=False)
    op.add_column("jobs", sa.Column("credit_cost", sa.Integer(), server_default="1", nullable=False))
    op.add_column("jobs", sa.Column("voice_provider", sa.String(length=50), server_default="edge", nullable=False))
    op.add_column(
        "jobs",
        sa.Column(
            "voice_config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "voice_config")
    op.drop_column("jobs", "voice_provider")
    op.drop_column("jobs", "credit_cost")
    op.drop_index(op.f("ix_voice_clones_user_id"), table_name="voice_clones")
    op.drop_table("voice_clones")
    # ### end Alembic commands ###
